// Pre-generated by scripts/build-bloom.ts from:
// SecLists/Passwords/Common-Credentials/10-million-password-list-top-10000.txt
// Run: bun run build:bloom  to regenerate with the full 10k list.
//
// When BLOOM_DATA is an empty string, the BloomFilter falls back to building
// itself at runtime from FALLBACK_LIST (development mode, ~100 passwords).

export const BLOOM_BIT_SIZE = 95_852;
export const BLOOM_HASH_COUNT = 7;

// Replace this value by running: bun run build:bloom
export const BLOOM_DATA: string = '';

// Top-100 most common passwords used as a development-mode fallback
export const FALLBACK_LIST: readonly string[] = [
  'password', 'password1', 'password123', '123456', '12345678', '1234567890',
  '1234567', '12345', '1234', '123', 'qwerty', 'qwerty123', 'qwerty1',
  'abc123', 'letmein', 'welcome', 'admin', 'admin1', 'admin123', 'login',
  'guest', 'test', 'test1', 'master', 'dragon', 'baseball', 'football',
  'monkey', 'shadow', 'sunshine', 'princess', 'superman', 'batman',
  'michael', 'jessica', 'iloveyou', 'trustno1', '111111', '1111111',
  '11111111', '000000', '123321', '123123', '654321', '666666', '888888',
  '7777777', '12341234', '1q2w3e4r', 'q1w2e3r4', 'zxcvbn', 'asdfgh',
  'qwertyuiop', 'passw0rd', 'p@ssword', 'p@ssw0rd', 'P@ssw0rd', 'pass',
  'secret', 'mypass', 'mypassword', 'changeme', 'letme1n', 'acc3ss',
  'hello', 'hello123', 'love', 'fuckyou', 'asshole', 'killer', 'hunter',
  'ranger', 'buster', 'matrix', 'starwars', 'pokemon', 'nintendo',
  'hack', 'hacker', 'server', 'network', 'internet', 'computer', 'system',
  'windows', 'linux', 'cisco', 'oracle', 'root', 'toor', 'abc', 'abcd',
  'abcde', 'abcdef', 'abcdefg', 'qazwsx', 'zxcvbnm', 'asdfghjkl',
  'poiuytrewq', 'lkjhgfdsa', '1q2w3e', 'q1w2e3',
];
