/**
 * Build script: generates the Bloom filter data from the SecLists top-10000
 * common passwords list and writes it to src/strength/common-passwords.ts.
 *
 * Usage: bun run build:bloom
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SECLISTS_URL =
  'https://raw.githubusercontent.com/danielmiessler/SecLists/refs/heads/master/Passwords/Common-Credentials/xato-net-10-million-passwords-100000.txt';

const BIT_SIZE = 95_852;
const HASH_COUNT = 7;


function fnv1a(str: string, seed: number): number {
  let h = (0x811c9dc5 ^ seed) >>> 0;
  for (let i = 0; i < str.length; i++) {
    h ^= str.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h % BIT_SIZE;
}

function buildFilter(words: string[]): Uint8Array {
  const bits = new Uint8Array(Math.ceil(BIT_SIZE / 8));
  for (const word of words) {
    const lower = word.toLowerCase().trim();
    if (lower.length === 0) continue;
    const h1 = fnv1a(lower, 0x00000000);
    const h2 = fnv1a(lower, 0xdeadbeef);
    for (let i = 0; i < HASH_COUNT; i++) {
      const pos = (h1 + i * h2) % BIT_SIZE;
      bits[Math.floor(pos / 8)]! |= 1 << pos % 8;
    }
  }
  return bits;
}

function toBase64(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes));
}


async function main(): Promise<void> {
  console.log(`Fetching password list from SecLists…`);

  const res = await fetch(SECLISTS_URL);
  if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);

  const text = await res.text();
  const words = text.split('\n').filter((w) => w.trim().length > 0);
  console.log(`Loaded ${words.length} passwords.`);

  const bits = buildFilter(words);
  const base64 = toBase64(bits);

  const outPath = join(import.meta.dirname, '../src/strength/common-passwords.ts');

  const content = `// Auto-generated by scripts/build-bloom.ts,  do not edit manually.
// Source: ${SECLISTS_URL}
// Generated: ${new Date().toISOString()}
// Passwords: ${words.length} | Bits: ${BIT_SIZE} | Hash functions: ${HASH_COUNT}

export const BLOOM_BIT_SIZE = ${BIT_SIZE};
export const BLOOM_HASH_COUNT = ${HASH_COUNT};
export const BLOOM_DATA: string = '${base64}';

// Fallback list is unused when BLOOM_DATA is populated.
export const FALLBACK_LIST: readonly string[] = [];
`;

  writeFileSync(outPath, content, 'utf8');
  console.log(`✓ Bloom filter written to ${outPath}`);
  console.log(`  Size: ${(base64.length / 1024).toFixed(1)} KB (base64)`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
